# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy application source
COPY . .

# Expose port if needed (not necessary for stdio transport)

# Use node to run the MCP server in stdio mode
CMD [ "node", "index.js", "stdio" ]
